@startuml
hide empty members
hide empty methods

package investigation {

    class CriminalOffence {
    }

    class OffenceAdvice {
    }

    class PoliceInvestigation {
    }

    class PreChargeDecision {
        void recordAlternativeOffenceAdvice(Suspect, OffenceAdvice)
        OffenceAdvice getOffenceAdviceFor(Suspect)
    }

    class Suspect    {
    }

}

package preparation{
}

class CriminalCase {
}

class PNCId {
}

class PublicProsecutionService {
}

Suspect *-- "*" CriminalOffence

PoliceInvestigation *-- "*" Suspect

PoliceInvestigation *-- PNCId

PreChargeDecision *-- "*" Suspect

PreChargeDecision *-- "*" OffenceAdvice

CriminalCase *-- PNCId

CriminalCase *-- "*" Suspect

PublicProsecutionService --> CriminalCase : <<creates>>

PublicProsecutionService --> PoliceInvestigation : <<uses>>
@enduml
