@startuml
hide empty members
hide empty methods

class CriminalCase {
}

class CriminalOffence {
}

class OffenceAdvice {
}

class PNCId {
}

class PoliceInvestigation {
}

class PreChargeDecision {
    void recordAlternativeOffenceAdvice(Suspect, OffenceAdvice)
    OffenceAdvice getOffenceAdviceFor(Suspect)
}

class Suspect    {
}

Suspect *-- "*" CriminalOffence

PoliceInvestigation *-- "*" Suspect

PoliceInvestigation *-- "*" PNCId

PreChargeDecision *-- "*" Suspect

PreChargeDecision *-- "*" OffenceAdvice

@enduml
